//
// Created by fakys on 06.10.2026.
//

#ifndef AVRDEVICECONTROLLER_ABSTRACTINTEGERCONFIGFILELDTYPE_H
#define AVRDEVICECONTROLLER_ABSTRACTINTEGERCONFIGFILELDTYPE_H
#include "AbstractConfigType.h"

class IntegerConfigFieldType : public AbstractConfigType {

};

#endif //AVRDEVICECONTROLLER_ABSTRACTINTEGERCONFIGFILELDTYPE_H
